version: 2.1

jobs:
  one-password-agent-build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:current
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - checkout
      - run:
          name: "Build One Password Run Image"
          environment:
            VERSION: "0.0.1"
          command: >
            echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin &&
            docker build -t "$DOCKER_USER/1password-cli:$VERSION" -f one_password/Dockerfile one_password/. &&
            docker push "$DOCKER_USER/1password-cli:$VERSION"

workflows:
  one-password-agent:
    jobs:
      - one-password-agent-build:
          context: docker-hub-creds
